name = "[HT] Carryall Backpack Plus";
picture = "banner.paa";
actionName = "Website";
action = "http://www.velocitientertainment.com/";
logo = "logo.paa";
tooltip = "Infinit Backpack Storage";
overview = "Velociti Entertainment has created a Wonderful Carryall Backpack to use on Servers! Check them out at the Website. This is mainly used on Server that allow Clients to install whatever mods they want. Please DO NOT ABUSE!!!";
description = "An Addon for Clients" ;
author = "Velociti Entertainment";